### ISSUE TITLE
Invalid Language code

### ISSUE THREAD

**Issue by wdebusschere** [DeuxHuitHuit/frontend_localisation#29]
I'm doing some SEO audit and some sites display this error as the site image.., never got on my browser..

![image](https://cloud.githubusercontent.com/assets/4136426/11961834/a3ce3358-a8db-11e5-885a-825517829021.png)

**Comment by wdebusschere** [comment]
Anyone?

**Comment by nitriques** [comment]
Hey @wdebusschere please update this extension as well as `flang_redirection` as it should fix your issue!

**Comment by wdebusschere** [comment]
Fixed! Thank you

**Comment by nitriques** [comment]
:+1:

**Comment by wdebusschere** [comment]
Symphony CMS version 2.6.7
Frontend localisation extension version 2.7.1
FLang detection gtlds extension version 2.0.0
Frontend Localisation Redirection version 2.0.0

The symphony log is full with
02/11/2016 7:42 pm > UNKNOWN: Exception 0 - Invalid language code. on line 331 of /Users/xxx/Sites/www.xxx.com/extensions/frontend_localisation/lib/class.FLang.php

Every time there is no language code in the url and before the Frontend Localisation Redirection happens, we get an entry in our symphony log. Is this on purpose?

**Comment by nitriques** [comment]
No. I though I'd fixed it.

Do the url has a `-` in it ?

It might also have to be this: https://github.com/DeuxHuitHuit/flang_redirection/blob/05c88e72bc596dbcff997fafa59f1e0480dde311/events/event.flang_redirect.php#L158 ?

**Comment by wdebusschere** [comment]
No - in the url.
All our sites have this in the logs..
The error comes from the  line 331 of /Users/xxx/Sites/www.xxx.com/extensions/frontend_localisation/lib/class.FLang.php

**Comment by wdebusschere** [comment]
Just did a fresh symphony install with the latest extensions for multilanguages. 

**Problem1:**
When i go to the site the symphony error log gets:
( extension is working fine)
11/03/2016 9:22 pm > UNKNOWN: Exception 0 - Invalid language code. on line 331 of /Users/xxx/Sites/symphony267/extensions/frontend_localisation/lib/class.FLang.php

After removing https://github.com/DeuxHuitHuit/flang_redirection/blob/05c88e72bc596dbcff997fafa59f1e0480dde311/events/event.flang_redirect.php#L158 ?
The error is gone.

**Problem 2:**
 When i go on the frontend to for example the french version, in the symphony log i get: 
11/03/2016 9:43 pm > Fatal Error: The selected language, fr, could not be found. Using default English dictionary instead.
After installing french language extension the error is gone, but prefer not to install too much extensions, is this error necessary on the frontend side?

**Comment by nitriques** [comment]
> Problem1:

Fixed in the new 2.0.1 flang_redirection release

> Problem 2:

It's not really a problem, since it's not a real "fatal error". It comes from this: https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.lang.php#L285

Great thing: this warning can be suppress, as I did in 45484bb.

Released in 2.7.2
