### ISSUE TITLE
Cannot get region or language to be recognized

### ISSUE THREAD

**Issue by kirkstrobeck** [DeuxHuitHuit/frontend_localisation#31]
We’re doing some multilingual, but can’t get frontend-localization https://github.com/DeuxHuitHuit/frontend_localisation to recognize the region
https://github.com/klaftertief/language_redirect will recognize the region and lang, but will not set the language in <fl-language>

Any tips on how to proceed?

---

Here is my multilingual stack

- FLang detection gTLDs Select FLang detection gTLDs Extension  1.2.0 Enabled GitHub  Vlad Ghita
- Frontend Localisation Select Frontend Localisation Extension  2.6.6 Enabled GitHub, Discuss Deux Huit Huit, Vlad Ghita
- Frontend Localisation Redirection Select Frontend Localisation Redirection Extension  1.2.6 Enabled GitHub, Wiki, Issues  Deux Huit Huit
- Languages Select Languages Extension  1.2.1 Enabled GitHub  Deux Huit Huit, Vlad Ghita

`.htaccess` looks like 

    RewriteRule ^(en|fr|de|es)-?()?\/(.*\/?)$ index.php?fl-language=$1&fl-region=$2&symphony-page=$3&%{QUERY_STRING} [L]

---

When I visit `/fr-gb/?debug` it is added to `<p1>fr-gb</p1>` (which is the first page parameter), and `fl-languages` looks like

```xml
<fl-languages>
        <current-language handle="en" language="en" region="">English</current-language>
        <supported-languages>
            <item handle="en" main="yes">English</item>
            <item handle="fr">Français</item>
            <item handle="de">Deutsch</item>
            <item handle="es">Español</item>
        </supported-languages>
    </fl-languages>
```

---

What I expect is that the first URL parameter is empty and that the language and region are detected and set in the XML. For example, the above shows a `fr` link, but Symphony is still sending along `en`.

**Comment by kirkstrobeck** [comment]
@nitriques any way to pay for the issue resolution? It’s important for an active project.

**Comment by nitriques** [comment]
Remove https://github.com/klaftertief/language_redirect  and install Languages ?

**Comment by nitriques** [comment]
Do you have PAGE_LHANDLES ?

Do you have the strict option active ?

**Comment by kirkstrobeck** [comment]
1. I don’t have language_redirect installed, so yes it is removed (that was an old comment before you mentioning to use frontend localization redirect)
2. Languages is installed
3. I do not have PAGE_LHANDLES
4. I do not know what strict option is 

---

Here are my extensions

- Association Field Select Association Field Extension  1.0.1 Enabled GitHub  Symphony Team
- Association Output Select Association Output Extension  1.2.0 Enabled GitHub  Büro für Web- und Textgestaltung
- Association UI: Editor Select Association UI: Editor Extension  1.1.0 Enabled GitHub  Büro für Web- und Textgestaltung
- Association UI: Selector Select Association UI: Selector Extension  1.2.1 Enabled GitHub  Büro für Web- und Textgestaltung
- Author Roles Select Author Roles Extension  1.2 Enabled GitHub  Twisted Interactive
- Cacheable Datasource Select Cacheable Datasource Extension  2.2.0 Not installed GitHub  Symphony Community, Nick Dunn
- CacheLite Select CacheLite Extension  1.3.2 Enabled GitHub  Symphony Community
- Conditionalizer Select Conditionalizer Extension  1.3 Enabled GitHub, Discuss, Issues Marcin Konicki
- Cross-Site Scripting (XSS) Filter Select Cross-Site Scripting (XSS) Filter Extension  1.4.1 Enabled GitHub  Symphony Team
- Date and Time Select Date and Time Extension  3.5.3 Enabled GitHub, Discuss Büro für Web- und Textgestaltung, Nils Hörrmann
- Debug Devkit Select Debug Devkit Extension  1.3.3 Enabled GitHub  Symphony Team, Rowan Lewis
- Duplicate Entry Select Duplicate Entry Extension  1.4 Enabled, requires Symphony 2.5.x  GitHub, Discuss Symphony Community, Nick Dunn
- Duplicate Section Select Duplicate Section Extension  1.2 Enabled GitHub, Discuss Solutions Nitriques, Deux Huit Huit, Pascal Piche
- Export Ensemble Select Export Ensemble Extension  2.2.0 Not installed GitHub, Discuss Symphony Team, Stephen Bau
- Field: Color Chooser Select Field: Color Chooser Extension  1.6.1 Enabled GitHub, Discuss Deux Huit Huit, Josh Nichols, Vlad Ghita, Pascal Piche
- Field: Image Upload Select Field: Image Upload Extension  1.6.5 Enabled GitHub, Discuss Vlad Ghita, Deux Huit Huit
- Field: Multilingual File Upload Select Field: Multilingual File Upload Extension  2.0.2 Enabled GitHub, Discuss Vlad Ghita, Deux Huit Huit
- Field: Multilingual Image Upload Select Field: Multilingual Image Upload Extension  2.0.2 Enabled GitHub, Discuss Vlad Ghita, Deux Huit Huit
- Field: Multilingual Text Box Select Field: Multilingual Text Box Extension  3.5.5 Enabled GitHub, Discuss Deux Huit Huit, Vlad Ghita
- FLang detection gTLDs Select FLang detection gTLDs Extension  1.2.0 Enabled GitHub  Vlad Ghita
- Frontend Localisation Select Frontend Localisation Extension  2.6.6 Enabled GitHub, Discuss Deux Huit Huit, Vlad Ghita
- Frontend Localisation Redirection Select Frontend Localisation Redirection Extension  1.2.6 Enabled GitHub, Wiki, Issues  Deux Huit Huit
- HTML5 Doctype Select HTML5 Doctype Extension  1.3.3 Enabled GitHub, Discuss Symphony Community, Stephen Bau
- Just In Time (JIT) Image Manipulation Select Just In Time (JIT) Image Manipulation Extension  1.44  Enabled GitHub, Discuss Symphony Team
- Languages Select Languages Extension  1.2.1 Enabled GitHub  Deux Huit Huit, Vlad Ghita
- Logs DevKit Select Logs DevKit Extension  1.1 Not installed GitHub, Discuss Symphony Community, Rowan Lewis
- Maintenance Mode Select Maintenance Mode Extension  1.9.1 Not installed GitHub, Discuss Symphony Team
- Markdown Text Formatter Select Markdown Text Formatter Extension  1.21  Enabled GitHub  Symphony Team
- Multilingual Select Multilingual Extension  1.1.0 Not installed GitHub  Jens Scherbl
- Profile Devkit Select Profile Devkit Extension  1.5.2 Enabled GitHub, Discuss, Issues Symphony Team, Rowan Lewis
- Reflection Field Select Reflection Field Extension  1.4.2 Enabled GitHub, Discuss Symphony Community, Rowan Lewis
- Remote Datasource Select Remote Datasource Extension  2.2.1 Enabled GitHub, Discuss, Issues Symphony Team
- Rich Text (TinyMCE) Text Formatter Select Rich Text (TinyMCE) Text Formatter Extension  2.2 Enabled GitHub, Discuss Symphony Community
- Select Box Link Field Select Select Box Link Field Extension  1.34  Not installed GitHub, Discuss Symphony Team
- Text Box Select Text Box Extension  2.5.3 Enabled GitHub, Discuss Symphony Community, Rowan Lewis
- XML Importer Select XML Importer Extension  2.2 Enabled GitHub, Discuss Rowan Lewis, Nick Dunn, Brendan AbbottSymphony 2.6.7

**Comment by nitriques** [comment]
Well, since you have a parameter on your index page (which you should try to avoid) and do not have https://github.com/DeuxHuitHuit/page_lhandles it normal that it's not working.

You need https://github.com/DeuxHuitHuit/page_lhandles to make that work. Sorry I haven't figured it out earlier.

**Comment by kirkstrobeck** [comment]
@nitriques unfortunately that doesn’t change the situation. There is nowhere in the preferences page to enter a language code, only language. I want to specify a region and see nowhere to do it. If I specify `/en-us/` it redirects to `/en/en-us/`

**Comment by nitriques** [comment]
Does it works if you specify the name of your index page ?

`/en-us/index/` ?

**Comment by kirkstrobeck** [comment]
No, that directs to `/en/en-us/index/`

**Comment by kirkstrobeck** [comment]
If you email me kirk@strobeck.com I can give you credentials if you’d like to take a look around

**Comment by nitriques** [comment]
I'll first try to replicate on a dev setup and if it works, I'll ask for credentials ;) You can send me PGP encrypted mail, here's my key: https://keybase.io/nitriques/key.asc

**Comment by nitriques** [comment]
And if you remove the redirect event, does it works when typing in the localized url ?

**Comment by kirkstrobeck** [comment]
http://cl.ly/gc8R -- `/en-us/` goes to a new route as the first parameter is now `/en-us/`

**Comment by nitriques** [comment]
I've spent a couple hours yesterday and I was puzzled... I am not sure how to properly fix it, but I came up with a solution that should work.

First, the regexp is wrong: the second group match will always match nothing, hence your problem. You need to add all region separated by a | like so:

```
RewriteRule ^(en|fr|de|es)-?(us|uk)?\/(.*\/?)$ index.php?fl-language=$1&fl-region=$2&symphony-page=$3&%{QUERY_STRING} [L]
```

The rewrite rule is created using region, but it looks like we are missing:

1. [ ] The UI to set regions
1. [ ] Adapted the rule at each save 

Sorry that it took so long: we are pretty busy at work and since we do not use regions, never needed it to work.

**Comment by kirkstrobeck** [comment]
Thank you so much for taking a look!

Unfortunately, that still does not address the issue. Using that rewrite rule, `/en-us/` still redirects to `/en/en-us/`

**Comment by nitriques** [comment]
Hum that's weird.

what's in your config.php ?

**Comment by nitriques** [comment]
if you are still willing to pay to make me fix it faster, I am open to it

**Comment by nitriques** [comment]
This is fixed as part of https://github.com/DeuxHuitHuit/frontend_localisation/releases/tag/2.7.0.

Thanks again Kirk for you support on this.
